// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wex.Context;

namespace Wex.Context.Migrations
{
    [DbContext(typeof(WexContext))]
    [Migration("20190219022533_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wex.Context.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Height");

                    b.Property<int>("ImageType");

                    b.Property<int?>("PostId");

                    b.Property<string>("Url");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Wex.Context.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<long>("CreatedUtc");

                    b.Property<string>("Domain");

                    b.Property<bool>("IsMeta");

                    b.Property<bool>("IsSelf");

                    b.Property<bool>("IsVideo");

                    b.Property<string>("LinkFlairText");

                    b.Property<string>("LinkFlairType");

                    b.Property<string>("Name");

                    b.Property<string>("Permalink");

                    b.Property<bool>("Pinned");

                    b.Property<string>("RedditId");

                    b.Property<string>("SelfText");

                    b.Property<bool>("Stickied");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Wex.Context.Models.Image", b =>
                {
                    b.HasOne("Wex.Context.Models.Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId");
                });
#pragma warning restore 612, 618
        }
    }
}
